### ISSUE TITLE
proton get account <account name> returns error

### ISSUE THREAD

**Issue by tommccann777** [ProtonProtocol/proton-cli#6]
I'm using @proton/cli/0.1.67 darwin-x64 node-v14.15.4 on MacOS Monterey version 12.3.1
No issues installing via NPM

Some commands work, some, including `proton get account <any account name>`

returns this error:     "ReferenceError: AbortController is not defined"

**Comment by jafri** [comment]
Use NodeJs 16

The command is

proton account NAME
